= MetalLB: A Commodore component to manage MetalLB

{doctitle} is a Commodore component for managing MetalLB.
The component is based on the official https://artifacthub.io/packages/helm/metallb/metallb[Helm Chart].

[CAUTION]
====
Currently there is no support for taking over an existing installation based on the https://metallb.universe.tf/installation/[official guide]
====


See the xref:references/parameters.adoc[parameters] reference for further details.

== Prerequisites

A memberlist key must be generated and stored inside the secret key management.

A pre-generated key ensures that the manifests can be applied multiple times without the secret key changing.
Otherwise, elevated fail-over rates may occur during manifest application, as the speakers can not communicate during the rollout, due to differing keys.

```
vault kv put -cas=0 clusters/kv/${TENANT_ID}/${CLUSTER_ID}/metallb-memberlist secretkey="$(openssl rand -base64 128)"
```

== Layer2 Mode (default)

For a minimal configuration, only a CIDR defining the VIP range is required.

```
parameters:
  metallb:
    addresses:
      - 10.128.1.200/32
```

== BGP Mode

The BGP mode can be configured by providing appropriate config:

```
parameters:
  metallb:
    bgpPeers:
      my-peer:
        spec:
          peerAddress: 10.0.0.1
          peerASN: 64501
          myASN: 64500
    ipAddressPools:
      bgp-pool1:
        spec:
          addresses:
            - fc00::/7
            - 10.128.1.192/27
    bgpAdvertisements:
      bgp-pool1:
        spec:
          ipAddressPools:
            - bgp-pool1

```

Check the https://metallb.universe.tf/configuration/#bgp-configuration[official documentation] for more details.
