= Parameters

The parent key for all of the following parameters is `metallb`.


== `namespace`

[horizontal]
type:: string
default:: `syn-metallb`



== `speaker.secretkey`

[horizontal]
type:: string
default:: Vault reference

A vault reference pointing to the Vault secret containing the secret key.
If the key isn't provided as a vault reference, the secret key must be provided in its base64 encoded form.
It can be generated using the command `openssl rand -base64 128`.

== `addresses`

[horizontal]
type:: list

A list of CIDRs MetalLB is using as a pool to assign transferable virtual IPs whenever a new service of type `LoadBalancer` is created.

Valid values are a single IP `10.128.1.200/32` or multiple addresses sepcified `10.128.1.192/27` / `192.168.1.240-192.168.1.250`.

When the cluster and the network infrastucture supports it, IPv6 CIDRs can be configured as well.

If the parameter addresses is provided, an address pool called `default` in protocol mode `layer2` is created.

See the https://metallb.universe.tf/configuration/#layer-2-configuration[MetalLB documentation] for more details.


== `config`

[horizontal]
type:: dictionary

A custom config can be provided.
This overrides the automatic config generation.

NOTE: The component doesn't validate the provided configuration.

For example this allows to specify multiple address pools:
```
    config:
      address-pools:
        - name: pool1
          protocol: layer2
          addresses:
            - 10.128.1.200/32
        - name: pool2
          protocol: layer2
          addresses:
            - 10.128.2.200/32
```

See the https://metallb.universe.tf/configuration/[MetalLB documentation] for more details.


== `charts.metallb`

[horizontal]
type:: helm chart version
default:: 0.1.23

A specific chart version. See the https://kapitan.dev/external_dependencies/#helm-type[kapitan documentation] for more information.
