= Parameters

The parent key for all of the following parameters is `metallb`.


== `namespace`

[horizontal]
type:: string
default:: `syn-metallb`



== `speaker.secretkey`

[horizontal]
type:: string
default:: Vault reference

A vault reference pointing to the Vault secret containing the secret key.
If the key isn't provided as a vault reference, the secret key must be provided in its base64 encoded form.
It can be generated using the command `openssl rand -base64 128`.

== `addresses`

[horizontal]
type:: list

A list of CIDRs (for example a single IP `10.128.1.200/32` or multiple addresses `10.128.1.192/27`) used as transferable virtual IPs.

IPv6 CIDRs are valid. The cluster and the network infrastucture must support it.

If the parameter addresses is provided, an address pool called `default` in protocol mode `layer2` is created.


== `config`

[horizontal]
type:: dictionary

A custom config can be provided.
This overrides the automatic config generation.

NOTE: The passed configuration is not going to be validated by the component.

For example this allows to specify multiple address pools:
```
    config:
      address-pools:
        - name: pool1
          protocol: layer2
          addresses:
            - 10.128.1.200/32
        - name: pool2
          protocol: layer2
          addresses:
            - 10.128.2.200/32
```


== `charts.metallb`

[horizontal]
type:: helm chart version
default:: 0.1.23

A specific chart version. See the https://kapitan.dev/external_dependencies/#helm-type[kapitan documentation] for more information.
